version: '3.3'
services:
  # mongodb:
  #   image: mongo:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data_container:/data/db
  #   restart: always

  # api: 
  #   image: credit-backend:0.1
  #   volumes:
  #     - ../credit-backend:/app
  #     - ../credit-backend/node_modules:/app/node_modules
  #   ports:
  #     - ${BACKEND_PORT}:${BACKEND_PORT}
  #   env_file:
  #     - ../credit-backend/.env
  #   depends_on:
  #     - mongodb
    
  #   command: 'yarn start'

  #   restart: always

  kccm: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 23000:3000
    env_file:
      - .env
    # depends_on:
    #   - api
    command: yarn dev

    restart: always

# volumes:
#   mongodb_data_container:
